#!/bin/bash
# MIT License - Copyright (c) 2026 ThierryN - https://github.com/ThierryN/dominion-flow
#
# Auto-generate SKILLS-INDEX.md from the skills-library directory.
# Run from the plugin root: bash scripts/generate-skills-index.sh
#
# This ensures the index always matches what's actually on disk.

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$PLUGIN_ROOT/skills-library"
OUTPUT="$SKILLS_DIR/SKILLS-INDEX.md"

if [ ! -d "$SKILLS_DIR" ]; then
    echo "[ERROR] skills-library directory not found at $SKILLS_DIR"
    exit 1
fi

# Count total skills (excluding index files and non-skill .md files)
TOTAL=$(find "$SKILLS_DIR" -name "*.md" \
    -not -name "SKILLS-INDEX.md" \
    -not -name "SKILLS_LIBRARY_INDEX.md" \
    -not -name "AVAILABLE_TOOLS_REFERENCE.md" \
    -not -name "README.md" \
    | wc -l | tr -d ' ')

# Get version from plugin.json
VERSION=$(grep '"version"' "$PLUGIN_ROOT/plugin.json" | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')

# Start generating the index
cat > "$OUTPUT" << HEADER
# Skills Library Index

> Auto-generated by \`scripts/generate-skills-index.sh\`
> Last updated: $(date +%Y-%m-%d)
> Plugin version: v${VERSION}

## Summary

**Total skills on disk: ${TOTAL}**

---

## Categories

HEADER

# Find all category directories and generate entries
find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d | sort | while read -r dir; do
    DIRNAME=$(basename "$dir")

    # Skip hidden directories
    [[ "$DIRNAME" == .* ]] && continue

    # Count skills in this category
    COUNT=$(find "$dir" -name "*.md" -not -name "README.md" | wc -l | tr -d ' ')

    if [ "$COUNT" -eq 0 ]; then
        continue
    fi

    # Format category name (kebab-case to Title Case)
    TITLE=$(echo "$DIRNAME" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

    echo "### $TITLE ($COUNT skills)" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    # List each skill file
    find "$dir" -name "*.md" -not -name "README.md" | sort | while read -r file; do
        SKILL_NAME=$(basename "$file" .md)
        # Extract first line that looks like a heading for description
        DESC=$(grep -m 1 "^# " "$file" 2>/dev/null | sed 's/^# //' || echo "$SKILL_NAME")
        echo "- \`$SKILL_NAME\` — $DESC" >> "$OUTPUT"
    done

    echo "" >> "$OUTPUT"
done

# Also handle root-level .md files (not in subdirectories)
ROOT_SKILLS=$(find "$SKILLS_DIR" -maxdepth 1 -name "*.md" \
    -not -name "SKILLS-INDEX.md" \
    -not -name "SKILLS_LIBRARY_INDEX.md" \
    -not -name "AVAILABLE_TOOLS_REFERENCE.md" \
    -not -name "README.md" \
    | sort)

ROOT_COUNT=$(echo "$ROOT_SKILLS" | grep -c "." 2>/dev/null || echo 0)

if [ "$ROOT_COUNT" -gt 0 ]; then
    echo "### Root Level ($ROOT_COUNT skills)" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    echo "$ROOT_SKILLS" | while read -r file; do
        [ -z "$file" ] && continue
        SKILL_NAME=$(basename "$file" .md)
        DESC=$(grep -m 1 "^# " "$file" 2>/dev/null | sed 's/^# //' || echo "$SKILL_NAME")
        echo "- \`$SKILL_NAME\` — $DESC" >> "$OUTPUT"
    done

    echo "" >> "$OUTPUT"
fi

# Footer
cat >> "$OUTPUT" << FOOTER
---

*Generated automatically. Run \`bash scripts/generate-skills-index.sh\` to regenerate.*
FOOTER

echo "=== SKILLS INDEX GENERATED ==="
echo "  Total skills: $TOTAL"
echo "  Output: $OUTPUT"
echo "  Version: v$VERSION"
